name: docker
description: Builds and conditionally pushes a Docker image.

inputs:
  tags:
    description: "List of tags."
    required: true
  push:
    description: "Whether to push the built image to the registry."
    type: boolean
    required: true

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to ki-artifact-registries-cf08 project
      if: ${{ inputs.push == 'true' }}
      uses: google-github-actions/auth@v2.1.4
      id: auth
      with:
        workload_identity_provider: projects/137670451433/locations/global/workloadIdentityPools/docker-ar-pool-br2f/providers/docker-gh-provider
        service_account: ki-docker@ki-artifact-registries-cf08.iam.gserviceaccount.com
        token_format: "access_token"

    - name: Login to ki-artifact-registries-cf08 artifact registry
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: europe-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build and Push Image
      uses: docker/build-push-action@v6
      with:
        push: ${{ inputs.push == 'true' }}
        tags: ${{ inputs.tags }}
        context: app
