name: "Tofu Plan and Apply"

on:
  workflow_call:
    inputs:
      environment:
        description: "The GitHub environment."
        required: true
        type: string
      image_tag:
        description: "The Docker image tag for the Cloud Run service."
        required: true
        type: string

defaults:
  run:
    working-directory: tofu

jobs:
  tofu:
    name: Tofu
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Tofu version
        id: tofu-version
        run: echo "version=$(cat ../../.opentofu-version)" >> "$GITHUB_OUTPUT"

      - name: Setup Tofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ steps.tofu-version.outputs.version }}

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.4
        with:
          workload_identity_provider: ${{ vars.gh_gcp_workload_identity_provider }}
          service_account: ${{ vars.cicd_service_account }}

      - name: Tofu Init
        run: tofu init -var-file=./environments/${{ inputs.environment }}/${{ inputs.environment }}.tfvars -lock=${{ github.ref == 'refs/heads/main' }}

      - name: Print .terraform.lock.hcl content
        run: cat .terraform.lock.hcl

      - name: Tofu Format
        run: tofu fmt -check -recursive

      - name: Tofu Plan
        run: tofu plan -var-file=./environments/${{ inputs.environment }}/${{ inputs.environment }}.tfvars -var="cloud_run_container_image=${{ inputs.image_tag }}" -lock=${{ github.ref == 'refs/heads/main' }}

      - name: Tofu Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: tofu apply -auto-approve -var-file=./environments/${{ inputs.environment }}/${{ inputs.environment }}.tfvars -var="cloud_run_container_image=${{ inputs.image_tag }}"
